version: '3.7'
services:
  app:
    build:
      dockerfile: ./Docker/Go/Dockerfile
    container_name: go_app
    ports:
      - "80:8080"
    volumes:
      - ./:/app
  mysql:
    image: mysql:8
    container_name: go_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: example_db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: